### ISSUE TITLE
今天碰到困难 2016-02-29

### ISSUE THREAD

**Issue by sfetome** [sfetome/testtest#11]
* 把碰到的困难按单独问题，尽量小的粒度，建成 issue.
* 不建 issue 就是没有困难的意思，
* 没有困难又没有代码，就是在欺负老实人
* 没有任何信息状态更新，让人很抓狂
* 有困难说出来不丢脸

**Comment by sfetome** [comment]
把issue 这就当成留言本

**Comment by exre** [comment]
:-(

**Comment by exre** [comment]
`self.__dict__[child.tag] = child.text  # support only 1 level `
只持多级不会
