### ISSUE TITLE
AccessToken类load函数待完善

### ISSUE THREAD

**Issue by exre** [sfetome/testtest#14]
在调用get_access_token()测试中会出有错误提示`.(<open` file '<stderr>', mode 'w' at 0x7f6e1b1ca1e0>, "Error: <type 'exceptions.IOError'>")``
会导致重新从服务器请求access_token，而不是文件中。

**Comment by sfetome** [comment]
👍

**Comment by exre** [comment]
> 👍 <-- 这个字符电脑上显示不了，我下次不装逼用 emoji 写评论了。

我的也不能显示，然后我装了emoji-fonts，就可以显示了；）

**Comment by exre** [comment]
#30
