### ISSUE TITLE
客服接口有问题，不能创建客服

### ISSUE THREAD

**Issue by sfetome** [sfetome/testtest#37]
客服接口有问题，不能创建客服
错误提示
{ "errcode": 61451, "errmsg": "invalid parameter" }
文档说明是参数错误(invalid parameter) ，网上讨论说是微信测试账号问题，不能创建，暂时未能确定

**Comment by exre** [comment]
报61451错误的原因可能有：

1. 微信号不是认证的公众号
2. 还没启用多客服插件（公众平台->功能->添加功能插件）
3. 没有设置微信号（不是gh开头那个原始ID）
4. 没有填写正确的微信号："kf_account" : "test1@微信号"
5. 密码没有用md5处理（32个字节的字符串）
6. POST的JSON数据最后一行多了逗号（如果从API文档里复制粘贴这个JSON格式就中招了，我在这上面浪费了一个小时……）

[转自]：[http://cto.eguidedog.net/node/228](url)

**Comment by exre** [comment]
> POST数据示例如下：
> 
> {
>      "kf_account" : "test1@test",
>      "nickname" : "客服1",
>      "password" : "pswmd5",
> }

微信官方文档中，客服管理部分json示例最后一行都多一个，
需要去掉
{
     "kf_account" : "test1@test",
     "nickname" : "客服1",
     "password" : "pswmd5"
}

**Comment by exre** [comment]
腾讯客服答复，测试号是不能调用多客服接口的
![image](https://cloud.githubusercontent.com/assets/17256523/13904306/db9963c0-eed6-11e5-9eae-8f5ec7f70d2c.png)

来自：[http://bbs.csdn.net/topics/391006234?page=1](url)

**Comment by sfetome** [comment]
这条应该作为经验写到wiki上，写到客服管理
下面
