### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'menu.json'

### ISSUE THREAD

**Issue by sfetome** [sfetome/testtest#5]
一个空的 menu.json 也可以通过测试，测试用例有点不合适

**Comment by exre** [comment]
已修复。
测试中还有个(<open file '<stderr>', mode 'w' at 0x7f1613b001e0>, "Error: <type 'exceptions.IOError'>")错误提示。
暂未找到原因。

**Comment by exre** [comment]
#14
