### ISSUE TITLE
消息奇怪不回复

### ISSUE THREAD

**Issue by sfetome** [sfetome/testtest#6]
http://sfeto.org/weixin?signature=fb86f2d3b99d858b195151c6919320aa1bab8c94&timestamp=1456601777&nonce=1000689220&echostr=whataaaHHH

直接浏览器中访问能得到 whataaaHHH
但，用微信消息测试工具和客户端发消息都会失败。

101.226.103.72 - - [27/Feb/2016 15:48:11] "POST /weixin HTTP/1.1" 405 -
101.226.103.72 - - [27/Feb/2016 15:49:33] "POST /weixin HTTP/1.1" 405 -
101.226.103.72 - - [27/Feb/2016 15:49:44] "POST /weixin HTTP/1.1" 405 -

从 log 来看，微信的请求是发到了 vps 的，

**Comment by exre** [comment]
因为vps中没有对xml做解析处理返回给微信服务器。
浏览器中可以访问，是因为vps中只做了request的处理。
