### ISSUE TITLE
如何访问最新版本的 API 文档？

### ISSUE THREAD

**Issue by sfetome** [sfetome/testtest#64]

**Comment by exre** [comment]
#57 
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1418702138&token=&lang=zh_CN
才发现直接点击会打不开，复制粘贴到地址栏没问题，；-）

**Comment by sfetome** [comment]
赞，终于访问到最新版本了。

**Comment by exre** [comment]
哦，原来如此！
